### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by asmaljcelj** [RSO-skupina64/data-aggregation#5]
Implementira se endpointe, ki kličejo `admnistration` mikrostoritev:

- [x] `POST /prices` pokliče endpoint implementiran v https://github.com/RSO-skupina64/administration/issues/4
- [x] `POST /prices/shop` pokliče endpoint implementiran v https://github.com/RSO-skupina64/administration/issues/5
- [x] `POST /product` pokliče endpoint implementiran v https://github.com/RSO-skupina64/administration/issues/6
- [x] `DELETE /product` pokliče endpoint implementiran v https://github.com/RSO-skupina64/administration/issues/7
- [x] `PUT /product` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/8
- [x] `POST /product-shop/history` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/9
- [x] `DELETE /product-shop/history` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/10
- [x] `PUT /product-shop/history` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/11
- [x] `POST /shop` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/18
- [x] `DELETE /shop` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/19
- [x] `PUT /shop` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/20
- [x] `GET/shop/multi` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/23
- [x] `DELETE /user` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/21
- [x] `PUT /user` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/22
- [x] `POST /product-type` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/12
- [x] `DELETE /product-type` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/14
- [x] `PUT /product-type` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/13
- [x] `POST /role` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/15
- [x] `DELETE /role` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/17
- [x] `PUT /role` pokliče endpoint  implementiran v https://github.com/RSO-skupina64/administration/issues/16
