### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by asmaljcelj** [RSO-skupina64/data-aggregation#6]
Implementira se endpointe, ki kličejo `authentication` mikrostoritev:

- [x] `POST /register`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/authentication/issues/7
- [x] `POST /login`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/authentication/issues/8
- [x] `POST /logout`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/authentication/issues/9
- [x] `POST /check-user-role`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/authentication/issues/10
- [x] `GET /user`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/authentication/issues/11
- [x] `PUT /user`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/authentication/issues/12
- [x] `PUT /user-change-password`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/authentication/issues/13
