### ISSUE TITLE
Favorite products

### ISSUE THREAD

**Issue by asmaljcelj** [RSO-skupina64/data-aggregation#7]
Implementira se endpointe, ki kličejo `favorite-products` mikrostoritev:

- [x] `POST /favorite`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/favorite-products/issues/4
- [x] `DELETE /favorite`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/favorite-products/issues/5
- [x] `GET /favorite`, ki kliče endpoint implementiran v https://github.com/RSO-skupina64/favorite-products/issues/6
